# Generated by Django 5.2.3 on 2025-12-12 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("subreddit", models.CharField(max_length=200)),
                ("scraped_html", models.TextField(blank=True)),
                ("scraped_text", models.TextField(blank=True)),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scraped", "Scraped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="reddit_outreach.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
                "unique_together": {("product", "url")},
            },
        ),
        migrations.CreateModel(
            name="ProductUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("profile_url", models.URLField(max_length=500)),
                (
                    "reason_text",
                    models.TextField(
                        help_text="Substring of text that demonstrates the user actually uses the product"
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="reddit_outreach.productpage",
                    ),
                ),
            ],
            options={
                "ordering": ["-extracted_at"],
                "unique_together": {("product_page", "username")},
            },
        ),
    ]
