"""Add uniqueness constraint for ProductPage (product, url)."""

# Generated by Django 5.2.3 on 2025-12-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add ProductPage URL uniqueness constraint."""

    dependencies = [
        ("reddit_outreach", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productpage",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="productpage",
            constraint=models.UniqueConstraint(
                fields=("product", "url"), name="uniq_productpage_product_url"
            ),
        ),
    ]
